### ISSUE TITLE
Correct Human description

### ISSUE THREAD

**Issue by mtabacman** [PeterRudin-Burgess/NavigatorRPG#1]
> Humans may or may not be direct descendents of the human species on Earth. The recieve one tier in Self Awareness, one tier in Toughness and one tier in Physique.

should be

>Humans may or may not be direct **descendants** of the human species on Earth. **They** **receive** one tier in Self Awareness, one tier in Toughness and one tier in Physique.

**Comment by PeterRudin-Burgess** [comment]
Thank you, the rules have been updated.
